### ISSUE TITLE
Crear maquina en AWS para Odoo

### ISSUE THREAD

**Issue by ManuelStardust** [PEM-Humboldt/.github#304]
# Descripción

- Crear maquina de aws
- Instalar Odoo usando el docker-compose dispuesto en este [commit](http://192.168.11.78/pem/odoo/commit/f7ff13d4de2e2a21619051a735138e4fab3e17a5)

# Consideraciones

No usar el módulo creado en la rama `instalation` aún, no sabemos qué tan necesario será para las pruebas que queremos hacer para la línea de integración

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/.github/304?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by erikasv** [comment]
Se creó la máquina exitosamente, pero depronto quedó corta de recursos pues la noto muy lenta.

Se documentó la máquina en el repositorio de aws y se actualizó la documentación en el repo de odoo. Queda un [MR](http://192.168.11.78/pem/odoo/merge_requests/2) abierto
