### ISSUE TITLE
[Spike] Proxy para el stac

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#309]
# Descripción

El objetivo es limitar el acceso a las peticiones PUT y POST al STAC para que solo los investigadores puedan hacer modificaciones al servidor.

Buscar, documentar y socializar cuál sería la forma de conseguir esto. Algunas posibles estrategias es limitar por tipo de operación e IP, usando un header de autenticación, o una vpn. Al considerar cada opción, documentar también qué producto se usaría en cada caso teniendo en cuenta el uso de ortos usuarios y el soporte, por ejemplo, en BioTablero y BioModelos se usa un gateway en nodejs para verificar un header de autenticación

Se pueden documentar todas las opciones consideradas, pero debe haber una como la recomendada. En la próxima tarea se implementará la opción recomendada.

# Consideraciones
Para el seguimiento de esta tarea cuadrar el espacio a más tardar el jueves en la tarde.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/.github/309?planning-poker) with Zenhub @cazapatamar @denarch22 @ManuelStardust

**Comment by denarch22** [comment]
Se realiza la respectiva investigación la cual queda contenida en la siguiente carpeta: https://drive.google.com/drive/folders/1SEgDjwlGQbxz3rm6l4PsM_J13yr8-Jo6?usp=drive_link
