### ISSUE TITLE
Resolver problema de Chamilo

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#316]
# Descripción

Ricardo habló con Camilo y con Manuel del problema, ellos tienen los datos de acceso.

Agregar un acceso directo a la carpeta que les compartió Ricardo dentro de la carpeta del SiB en `Documentación Desarrollos Informáticos PEM`

# Consideraciones
- _**Tener mucho cuidado con los cambios que se hagan para probar porque Chamilo es muy frágil**_
- Comunicarse con Andrés Duarte para cualquier cosa o prueba que se necesite.

**Comment by ManuelStardust** [comment]
La versión de Chamilo usada es la 1.11.16, esta hecho sobre Symfony sin embargo no tiene instalada la consola de comandos de Symfony.

**Comment by ManuelStardust** [comment]
Es posible que el error se produzca cuando se hacen cambios de ciertos tipos de contenido y deba limpiarse el cache desde la aplicación, aunque no se pudo probar en esta ocasión. Para limpiar el cache se deben seguir los pasos del link puesto en el comentario anterior.

**Comment by erikasv** [comment]
Otra posible causa del problema es que los recursos que se mostraban en el home se almacenaban en la carpeta de documentos del curso 1. Ellos planean hacer pruebas luego para descartar esto
