### ISSUE TITLE
[Biab] Arreglar caso especial en creación de proyecto

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#320]
# Descripción

Resolver el hallazgo que impide crear un proyecto bajo el error de que el handle ya existe, dado que inicialmente se intentó crear con un campo relacionado ausente (no de la tabla de proyectos).

Se debe manejar un rollback, o hacer validaciones antes de intentar ingresarlo en la base de datos.

# Actualización 01-04-24
Se va a realizar el ajuste (optimización) sobre las consultas involucradas en la transacción para intentar mejorar el tiempo de la misma.

**Comment by ManuelStardust** [comment]
Se implementaron los ajustes para usar transacciones en mysql usando MeekroDB.
[PR](https://github.com/GEO-BON/bon-in-a-box/pull/208)

**Comment by jmlord** [comment]
This should affect update as well as upload. Currently these are two separate php files, bug the bugs are always mirrored.

We should consider making a single file to insert or update.
