### ISSUE TITLE
[Spike] Estrategia de backups para el STAC

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#323]
# Descripción

Crear un nuevo archivo en la raiz del repositorio [STAC](http://192.168.11.78/pem/STAC) para el tema de los backups del servidor STAC.

El documento debe contener el paso para sacar un backup de todo lo del servidor. Teniendo en cuenta: base de datos, assets (cog, tiff).

## Adicionales:
Agregar las recomendaciones de cambios en la implementación actual en una sección del mismo documento

# Consideraciones
- Tener en cuetna que depronto los asstes se organicen en carpetas, verificar si hay que tener en cuenta algún cambio para el backup de los mismos bajo este supuesto

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/.github/323?planning-poker) with Zenhub @cazapatamar @ManuelStardust @denarch22

**Comment by denarch22** [comment]
Se realiza el documento de la posible estrategia para realizar backup a los activos de stac, considerando los posibles casos como cuando la bd esta localmente en una máquina, o desde la nube como en tecnologías de Azure, adicional se considera contemplar mantener la bd de docker de postgres ya que esta contiene la estructura de datos de la bd de docker.

Se realiza la creación de una rama donde contiene este documento: http://192.168.11.78/pem/STAC/merge_requests/10

**Comment by denarch22** [comment]
Se realiza ajuste del documento según las especificaciones realizadas.

**Comment by denarch22** [comment]
Se realiza el merge en la rama según el visto bueno.
