### ISSUE TITLE
Odoo

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#324]
# Descripción

Jugar con Odoo para hacer las pruebas sobre los temas que se han hablado previamente. 

Después crear un repositorio en gitlab y documentar ahí los pasos para reproducir una instancia de odoo en la máquina local, de manera que quede con los mismos módulos activos, configuraciones, etc. en todos los casos.

Ahí mismo, en una carpeta dedicada (o como mejor se considere), versionar los archivos que deban ser ajustados, ya sea relacionados con la creación de un módulo, con una vista o con lo que sea.

# Consideraciones

- Agregar al repositorio todo lo que considere importante para que los demás miembros del equipo entiendan cómo funciona este tema
- Ideal buscar un espacio (puede ser en el siguiente sprint) para socializar más del tema de odoo

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/.github/324?planning-poker) with Zenhub @ManuelStardust

**Comment by ManuelStardust** [comment]
Se hicieron las actualizaciones en los permisos, archivo de docker compose y Readme según la revisión realizada con Erika para la instalación de módulos.
