### ISSUE TITLE
Error al descargar certificado en CR-SIB

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/.github#325]
# Descripción
Se reporta un error en [CR-SIB](https://biodiversidad.co/certificados/publicacion-permisos/login/?next=/) al descargar un certificado para un usuario específico. No sirve el botón de la descarga y el tooltip aparece y desaparece cuando se pone el cursor encima del botón.

<img width="366" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEhjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f8b80ed8d10d6c63388d8b68e0ce7d3c795a054/imagen.png" alt="imagen.png" />

Solo pasa con ese usuario. Se probó con otro usuario de prueba y descarga bien.

Las credenciales del usuario con el problema las tiene Camilo Zapata o Carolina Castro.

Las credenciales del usuario de prueba están en el documento `dejame salir` en el drive.

# Consideraciones
Para intentar reproducir el error, restaurar la base de datos en el ambiente local

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/.github/325?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by ManuelStardust** [comment]
Durante la exploración del código de la aplicación se encontro que el código actual de producción difiere del código en el repositorio, en producción se encuentra la rama dev y en al repositorios las ramas main y development que no comparten el historial con la rama del servidor, por tanto se decidio subir al código actual del servidor a una rama dentro del repositorio para poder compararlas.
