### ISSUE TITLE
Levantar ambiente local de CR-SiB

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#326]
# Descripción

Levantar un ambiente local de CR-SiB

1. Preguntar a Ricardo si hay razones para no tener readme en el [repo de certificados](https://gitlab.com/sib-colombia/certificados-de-publicacion) y mantener las instrucciones de despliegue en el otro [repo](https://gitlab.com/sib-colombia/documentacion-productos-y-servicios/-/tree/master/CR-SiB). Y confirmar si podemos crear el readme para las instrucciones de desarrollo
2. Crear y/o ajustar instrucciones de desarrollo (ya sea en el repo de documentación o en el de certificados)

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/.github/326?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by ManuelStardust** [comment]
Se consiguió la instalación local de la herramienta. Sin embargo se genero un conflicto con las librerias de Python lxml y reportlab, por tanto para efectos de pruebas iniciales se instalo la herramienta sin estas dos librerias.

Se creo un [MR](https://gitlab.com/sib-colombia/certificados-de-publicacion/-/merge_requests/2) en el repostorio con las instrucciones de instalación en local.

Las instrucciones de uso se pueden consultar en este [documento](https://drive.google.com/file/d/1L8Ce6gxG82wbVYGztIPxUWAR1vJHkeFf/view?usp=sharing). Inicialmente se recomienda consultar las secciones _creación de autoridades_ y _creación de certificados_.

**Comment by ManuelStardust** [comment]
Adicionalmente dentro de la revisión inicial de la plataforma se encontro una etiqueta rota en la plantilla principal de Django [templates/layouts/application.html](https://gitlab.com/sib-colombia/certificados-de-publicacion/-/blob/main/templates/layouts/application.html?ref_type=heads) línea 21. Se sube la corrección dentro del MR ya citado.
