### ISSUE TITLE
Revisar errores en IPT

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#328]
# Descripción

Se reportaron varios errores, entre ellos:
- Hay un IPT (el marino) que reporta 0 recursos
- El fin de semana llegó un correo indicando que se estaba mostrando error de Java relacionado con el espacio  en el IPT normal

Seguramente el problema sí es de espacio. Hablar con Ricardo en caso de que hayan dudas sobre qué borrar.

**Comment by cazapatamar** [comment]
Se liberan mas de 40 GB borrando backups viejos, se reinicia el contenedor y el servicio de docker. Aun no se ven los registros en el IPT.

Se necesita seguir revisando. Se sugiere hablar con Daniel S para ver si puede estar relacionado con un tema similar que se dió con el IPT de CEIBA hace algunos meses.

**Comment by cazapatamar** [comment]
Se revisa con TI (Daniel S), el hizo una revisiòn del servidor, del volumen de datos, de espacio, etc. No encontrò nada. Se reinicia varias veces la maquina virtual pero el resultado es el mismo.

**Comment by erikasv** [comment]
En scrum semanal del SiB se concluyó que no se va a intentar resolver más este problema y vamos a iniciar con este ipt para la migración al 3.0
