### ISSUE TITLE
Levantar ipt 3.0 para ipt marino

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#329]
# Descripción

Levantar un ipt 3.0.2 y migrar el ipt marino.

# Importante
- **Sacar backup de la carpeta de datos antes de iniciar el proceso**
- **_NO_** destruir el contenedor del ipt actual
- Detener el contenedor actual para evitar conflictos con los volúmenes
- Dar prioridad a esta tarea, para el miércoles a primera hora se debe tener la migración o las razones por las que no será posible hacerla

# Consideraciones

- https://ipt.gbif.org/manual/en/ipt/latest/releases#3-0-2-april-2024
- https://ipt.gbif-uat.org/manual/en/ipt/latest/release-notes
- https://ipt.gbif-uat.org/manual/en/ipt/latest/getting-started
- Buscar la documentación o instrucciones de despliegue en el gitlab del SiB para tener en cuenta pasos/configuraciones especiales. Ante dudas preguntar a Ricardo por más documentación.
- Verificar todos los volúmenes del contenedor actual, enlazar los mismos para el nuevo
- Ante dudas de configuración consultar a Esteban o Ricardo

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/.github/329?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by cazapatamar** [comment]
Se hicieron varias pruebas y aproximaciones de manera local y en el servidor cloud 1. Finalmente la que mejor funcionó fue esta: 

1. Realizar un despliegue "limpio" del contenedor de la version 3.0.2. Montar el volumen en el contenedor pero apuntando a un directorio vacio, que es donde se generará la estructura de archivos de la nueva version.
2. Realizar la configuración inicial sobre el IPT especificando un usuario administrador, url donde quedará desplegado, tipo de despliegue (TEST MODE para este ejercicio) y otros datos
3. Copiar los archivos manualmente de los recursos de la versión anterior (subcarpeta `resources`, y archivos `/config/users.xml` y `/config/registration2.xml`).
4. Entrar al panel administrador e instalar las extensiones que se encontraban en la version anterior
5. Reiniciar el contenedor

En este punto ya deberian poder verse todos los recursos y todos los usuarios anteriores deberian poder ingresar a la plataforma.

Queda faltando algunas cosas de estilos y personalización que se abordarán en otra tarea. Tambien queda pendiente revisar algo relacionado con los DOIs que mencionó Estaban que puede ser un problema en esta nueva versión 3.0.2.
