### ISSUE TITLE
Organizar repositorio de GitLab para CR-SiB 

### ISSUE THREAD

**Issue by ManuelStardust** [PEM-Humboldt/.github#332]
- Acutalizar el repositorio con los cambios presentes en el código de producción de la aplicación ya que estos cambios no se encuentran versionados en el repo actual (determinar la mejor forma de hacerlo intentando conservar el historial de cambios).

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/.github/332?planning-poker) with Zenhub @erikasv @ManuelStardust

**Comment by ManuelStardust** [comment]
Se creo la rama [develop](https://gitlab.com/sib-colombia/certificados-de-publicacion/-/tree/develop?ref_type=heads) donde se consolido todo el historial que estaba presente en el servidor de producción.

**Comment by erikasv** [comment]
@ManuelStardust la rama main tiene que quedar con los cambios finales para poder hacer la tarea #333.

Por el tema de los historiales diferentes no se puede evidenciar qué se mezclo con qué, entonces agregar un comentario explicando lo que hiciste.

Adicionalmente borrar las ramas que ya no sean necesarias

**Comment by ManuelStardust** [comment]
El código del repositorio no comparte historial con el que actualmente se encuentra en el servidor de producción, por tanto se mezclo el código presente en producción dentro de las ramas develop y main para conservar el historial del servidor.
