### ISSUE TITLE
CR-SIB: Arreglar problema con un usuario paa descargar sus certificados

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/.github#334]
Hay un usuario que tiene problemas para descargar sus certificados. Al hacer clic sobre cualquier certificado se genera el siguiente error:

<img width="696" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm1uQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e100f6d11a8bf8cc9280b9177d514febaa8f4716/imagen.png" alt="imagen.png" />

Por ahora solo se tiene detectado que pasa con ese usuario. Se revisó con el usuario de pruebas y no hay problema.

Datos
- usuario: info@gdel.com.co
- contraseña: En la sala `Tecnologías/Desarollo - SiB Colombia`

Se sugiere revisar este bug y el otro relacfionado con el tooltip la descarga del certificado despues de organizar las ramas y código fuente de la aplicacion CR-SIB.

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/.github/334?planning-poker) with Zenhub @erikasv @ManuelStardust

**Comment by cazapatamar** [comment]
Parece que habia un error con los datos del usuario. Caro Castro le creó un nuevo usuario y de alguna forma le asigno los certificados y ya funcionó. Se va a dejar esta tarea en el Icebox mientras se confirma que todo está en orden y si luego de una semana no se reporta nada extraño, se sugiere cerrar esta tarea.

**Comment by ManuelStardust** [comment]
En la reunión con el equipo del SiB se acordo que es un tema de procedimiento y no un error de plataforma, por lo que el equipo del SiB se va a dedicar a documentar el caso.
