### ISSUE TITLE
Liberar espacio para backups de ceiba

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#338]
# Descripción

Borrar backups los backups del año pasado, dejar 1 por mes (el del último día de cada mes).

# Consideraciones
- No se ha implementado la limpieza en el cronjob, si se desea puede hacerlo, pero debe hacer los ajustes necesarios para dejar 1 por mes. (ver [documento](https://docs.google.com/spreadsheets/d/1Y97v1KhdlD4-DwTZJvS1h8bHQ6p4LbKOgm_k5N-GSQk/edit#gid=0))
- Backups de ceiba: [gitlab](http://192.168.11.78/pem/datacenter-admin-info/blob/master/backups/ceiba/backup_ceiba.sh)

# Actualización 4 de junio
- Revisar que los backups diarios se esten ejecutando correctamente y probar la ejecución del backup mensual.

**Comment by ManuelStardust** [comment]
- Se eliminaron los backups del año 2023 del servidor, dejando únicamente los correspondientes a la última copia de cada mes.
- Se creo un [MR](http://192.168.11.78/pem/datacenter-admin-info/merge_requests/1) en el repositorio para eliminar los backups antiguos y generar el bakcup del último día del mes.

**Comment by ManuelStardust** [comment]
Se ejecuto el backup mensual el 31 de mayo, sin embargo la tarea no se completo por un problema de permisos con algunos directorios.

**Comment by ManuelStardust** [comment]
Se logró ejecutar el cron del backup mensual agregando una verificación para la creación del directorio, ademas se cambio el propietario de las carpetas ocultas para evitar errores al ejecutar los backups diarios y mensuales.

Se deja un [MR](http://192.168.11.78/pem/datacenter-admin-info/merge_requests/2) con los últimos ajustes.
