### ISSUE TITLE
Levantar gitlab en máquina local

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#339]
# Descripción

Tomar un backup del GitLab interno (sacarlo si o hay uno) y restaurarlo en una instancia en la máquina local.

Para esto revisar la documentación generada a partir de la tarea [319](https://github.com/PEM-Humboldt/.github/issues/319) y complementar cualquier paso o consideración necesaria.

# Consideración

Revisar también la documentación hecha de la tarea 319 (el documento) y ante cualquier duda o comentario hablarlo con Camilo

**Comment by ManuelStardust** [comment]
Se logró instalar docker de manera local y restaurar un backup con la información actual de repositorio. El comando para restaurar se dejo en la sección de gitlab del [documento del flujo de trababjo con repositorios](https://docs.google.com/document/d/1TGc0AX6aIhxKNArgszvij6KRoHZ0uYSzuTMfRvDDO-E)

**Comment by erikasv** [comment]
@ManuelStardust las instrucciones del documento dicen cómo restaurar un backup en el mismo contenedor, pero no dice nada de cómo crear una nueva instancia
