### ISSUE TITLE
Crear módulo para línea de integración en odoo

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#340]
Crear:

- manifest
- modelos
- vistas
- permisos

Tomar el primer módulo de referencia para saber cómo y dónde crear crear esos archivos

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/.github/340?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by cazapatamar** [comment]
Se avanzó en la revisión de la documentacion del gitlab, el despliegue local de odoo pero aparecieron algunos errores al instalar el plugin compose sobre docker. Me reuni con Manuel y me explico como y donde crear los archivos para este nuevo módulo.

**Comment by cazapatamar** [comment]
Se avanzó con instalación de odoo en local, con la ayuda de Manuel para configurar las variables de ambiente.
