### ISSUE TITLE
Plan para despliegue de IPT Marino

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#341]
Crear un plan de pasos para el despliegue del ipt marino. Documentarlo en el repositorio `Documentacion-EC-SiB-Colombia`, no sé si hay una carpeta o archivo adecuado para eso, pero si no, crearlo.

Tener en cuenta de incluir todo, desde la creación del contenedor hasta las personalizaciones a través del administrador y las que no se hayan podido hacer porque requieren edición del código o algo así.

Tomar como base las [instrucciones](https://gitlab.com/sib-colombia/documentacion-productos-y-servicios/-/blob/master/Protocolos%20de%20infraestructura/IPTs/upgrade_ipt_v3/actualizar_ipt_v3.MD?ref_type=heads) de despliegue para un ambiente de pruebas. Una opcion es crear una copia de estas instrucciones y complementarlas. Otra opción es agregar a estas instrucciones las cosas que aplican para producción especialmente en el punto 3.2 y personalizaciones de visualización.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/.github/341?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by cazapatamar** [comment]
Se suben al gitlab las [instrucciones](https://gitlab.com/sib-colombia/documentacion-productos-y-servicios/-/blob/migrateIPTVersion3Production/Aplicaciones%20del%20SiB%20Colombia/IPTs/upgrade_ipt_v3/actualizar_ipt_v3-PRUEBAS.MD?ref_type=heads) para despliegue en produccion.

Se esperan manitos arriba o sugerencias de cambios.
