### ISSUE TITLE
[BIAB] Error en la creación de proyectos

### ISSUE THREAD

**Issue by ManuelStardust** [PEM-Humboldt/.github#342]
Solucionar el error reportado en el PR para la creación de proyectos. [Implement Database Transactions for Project Creation](https://github.com/GEO-BON/bon-in-a-box/pull/208)

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/.github/342?planning-poker) with Zenhub @ManuelStardust

**Comment by ManuelStardust** [comment]
Logre hacer los ajustes para evitar los errrores reportados en el PR, sin embargo hace falta hacer pruebas.

**Comment by ManuelStardust** [comment]
Finalicé las pruebas de creación de poryectos y actualice el PR. Habia un inconveniente con el uso de Meekro DB para almacenar los datos geográficos, pero se logro solucionar.
