### ISSUE TITLE
Despliegue a producción IPT Marino 

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#343]
# Descripción

Llevar a producción el IPT marino. El miércoles 12 empezando la tarde (1 o 2).

**Importante**: Antes de empezar con las instrucciones documentadas en el gitlab, se debe sacar un backup.

Continuar alimentando la nueva pestaña de documentación de los servidores SiB

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/.github/343?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by cazapatamar** [comment]
Se hace el despluegue en produccion del ipt sib marino. Surgieron varios inconvenientes y fue necesario replantear varios puntos de las instrucciones planeadas originalmente.

Se actualiza documentación en el gitlab con los últimos cambios.
