### ISSUE TITLE
Actulalizar odoo en el servidor

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#347]
# Descripción
Actualizar la instancia de odoo que está en aws para que tenga el nuevo módulo desarrollado para la línea de integración.

Cargar los registros que hay actualmente en el excel para que se puedan ver en la aplicación

# Consideraciones
Si hay que tener en cuenta ajustes para la importación de los registros, documentarlos en un nuevo archivo en la raíz del repositorio [odoo](http://192.168.11.78/pem/odoo)

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/.github/347?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by cazapatamar** [comment]
Se actualiza la instancia de odoo y se suben los datos del excel de las solicitudes.

Se dejaron los campos lo mas similar al excel para poder mostrar el modulo y como funcionaria con los datos actuales. Ya si decidimos continuar con la implementación en la GIC, les podriamos hacer algunas sugerencias pequeñas para convertir algunos campos en seleccion multiple y y otros cambios menores.

Por ahora no se documentó nada acerca del cargue de datos ya que estos entraron practicamente directos, salvo 3 casos que se sugiere que se documente posteriorme te cuando se decida la estructura final del modulo y los tipos de campos. Para esta carga se tuvo en cuenta:

- Para los campos booleanos cambiar X por 1 y vacio por 0.
- Para los campor requeridos poner NA (o cualquier otro valor) en donde estuviera vacio.
- En la columna de fecha de solicitud y otros campos de fecha, habian unas `P` que se cambiaron por vacios ya que el campo no es requerido.

La funcion de importar datos es muy buena y ayuda a identificar facilmente los ajustes sobre los datos que es necesario hacer.

Se deja apagada la maquina mientras se decide el momento para mostrarlo a los de la GIC.
