### ISSUE TITLE
Preparación de odoo para línea de integración

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#348]
# Descripción

Realizar los siguientes ajustes:

- Que los contenedores inicien solos con la máquina, hacer esto editando la configuración de los contenedores https://docs.docker.com/reference/cli/docker/container/update/
- Crear usuario para la línea de integración. Este usuario debe tener permisos para manejar el módulo creado, pero no debe ser admin. Si es necesario, crear un nuevo grupo o perfil. Documentar todos los cambios que se hagan
- Corregir el paso 4 de las instrucciones de [instalación](http://192.168.11.78/pem/odoo#instalaci%C3%B3n-1) (el símobolo `<`no se está mostrando bien)

**Comment by cazapatamar** [comment]
Se ajusta el restart always en los contenedores
Se crea grupo y reglas de acceso para usuarios de solo el modulo de solcitudes
Se actualiza producción
Se crea un nuevo usuario para Carolina Castro
Se documenta todo en el readme del repo en el gitlab
