### ISSUE TITLE
Reevaluar el uso de stac-fastapi

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#349]
# Descripción

Hemos usado el repositorio de [Biodiversité Québec](https://github.com/BiodiversiteQuebec/stac-fastapi) para todo lo relacionado con nuestro servidor bajo STAC, principalmente porque es una aplicación funcional, que simplemente tuvimos que correr. Este incluye el backend de postgres, las extensiones necesarias para cumplir con la especificación y algunos scripts necesarios para orquestar todo.

Ahora tenemos la necesidad de restringir el acceso a las operaciones POST, PUT, DELETE, por lo tanto no podemos seguir usando el repositorio mencionado. Planeábamos sacar un fork y hacer los ajustes necesarios en nuestro repositorio, pero me he dado cuenta de que el fork de Biodiversité Québec está desactualizado y desconectado del repositorio principal, lo cual implica que para nosotros poder estar al día con el repositorio de [stac-utils](https://github.com/stac-utils/stac-fastapi) tendríamos que sacar un fork directamente y hacer los mismos ajustes que hicieron desde Biodiversité Québec.

Entonces nos volvemos a encontrar ante 3 opciones:
1. Descartar el uso del middleware directamente en stac-fastapi y usar un nuevo servicio intermedio para hacer de proxy (quitar el acceso directo al servidor stac)
1. Haer el fork de stac-fastapi y hacer todos los cambios necesarios, preferiblemente sobre la [versión 3](https://github.com/stac-utils/stac-fastapi/tree/release/v3.0.0b3) de una vez
1. Reevaluar el uso de stac-fastapi y probar [Franklin](https://azavea.github.io/franklin/), que tiene incluido la opción de configurar [autenticación](https://azavea.github.io/franklin/docs/0004-make-authentication-configurable-at-server-startup)

El objetivo de esta tarea es probar Franklin. Se debe tener en cuenta los siguientes puntos:
- Debe cumplir con la especificación del api de stac, es decir que los endpoints y respuestas deben ser iguales a lo que teníamos antes
- stac-data-tools debe funcionar de la misma forma sin requerir ningún cambio
- Debería tener el mismo rendimiento (pero no sé cómo probar eso)
- Verificar que la autenticación para las operaciones deseadas funcione correctamente

Como parte del resultado de esta tarea:
- renombrar el archivo [STAC_SERVER.md](http://192.168.11.78/pem/STAC/blob/master/STAC_SERVER.md) a `stac-fastapi.md`
- Crear un nuevo archivo y documentar ahí las instrucciones para poner a andar el servidor con Franklin
- Mejorar el readme del repositorio [STAC](http://192.168.11.78/pem/STAC), cambiar ese título `Utilitarios y documentación` y describir todos los archivos y carpetas que están en la raíz del repositorio

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/.github/349?planning-poker) with Zenhub @cazapatamar @denarch22

**Comment by cazapatamar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/.github/349?planning-poker) with Zenhub @ManuelStardust

**Comment by ManuelStardust** [comment]
Hasta el momento se logro hacer funcionar franklin con pgstac. Las peticiones tipo post, put, delete  estan bloqueadas,  así que para crear colecciones es necesario configurar la autenticación para seguir con las pruebas.
