### ISSUE TITLE
Levantar stac-fastapi desde el origen

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#351]
# Descripción

Debido a los inconvenientes encontrados con franklin en la tarea [349](https://github.com/PEM-Humboldt/.github/issues/349) debemos volver a usar stac-fastapi, ya he creado el [fork](https://github.com/PEM-Humboldt/stac-fastapi) para ellos.

Crear una nueva rama en la que hacer todos los cambios que se requieran, como archivos para docker compose, configuraciones de ambiente, ajustes al readme, etc. Posteriormente en esta rama se van a realizar los ajustes para la protección de los endpoints post, put y delete. Se debe levantar todo como lo tenemos ahora pero sin hacer uso del repositorio de Biodiversité Québec, se puede usar de base y tomar lo que se requiera (con la citación apropiada).

**Comment by ManuelStardust** [comment]
Se logro hacer las modificaciones para correr la aplicación con docker basandome en algunos de los ajustes del repositorio de Biodiversite Quebec. Estoy organizando el código y la documentación para subirlos en una rama.
