### ISSUE TITLE
Restaurar organizaciones en ipt permisos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#355]
Dedicar algo de tiempo a revisar logs y explorar el tema del cron para reiniciar el ipt en la madrugada

# Actualización 02/10/2024
Documentar el cronjob en un archivo nuevo en la carpeta [IPTs](https://gitlab.com/sib-colombia/documentacion-productos-y-servicios/-/tree/master/Aplicaciones%20del%20SiB%20Colombia/IPTs)

**Comment by ManuelStardust** [comment]
Se realizó la revisión y se encontro que solo existe una organización nombrada "No registrado" atada a todos los recursos registrados, se verificó con el equipo del SiB y así funciona porque este IPT no reporta a GBIF.

Se dejo un cron progamado en el servidor para reiniciar el IPT en las mañanas.

**Comment by ManuelStardust** [comment]
Se actualizó el cron para limpiar cache en el servidor y así mismo se documento el cron en el repositorio: [cronjobs_SIB_CLOUD3.md](https://gitlab.com/sib-colombia/documentacion-productos-y-servicios/-/blob/cd036bf3586779d5a5876bae0846e6c91a504f78/Aplicaciones%20del%20SiB%20Colombia/IPTs/cronjobs_SIB_CLOUD3.md)
