### ISSUE TITLE
Reorganizar readme del repositorio .github

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/.github#38]
# Descripción

Hacer ajustes al readme del repositorio por defecto de la organización para que sirva más de referencia cuando los investigadores necesiten ayuda (idealmente este año van a versionar más cosas).

Las cosas principales a ajustar son las siguientes, pero se pueden agregar otras que sean útiles:
- [x] Usar español
- [x] Cambiar el título del readme
- [x] Crear una sección de dudas (o de ayuda o de tips, como se considere mejor), por ahora debe incluir un enlace y tal vez una pequeña explicación sobre el uso de llaves ssh o tokens en lugar de contraseña para sincronizar los repositorios. Tener en cuenta las intrucciones de github https://dev.to/asjordi/configurar-llave-ssh-en-github-desde-windows-4h6i.
- [x] Por fa dejar el comic 😬
- [x] Cambiar los nombres de los enlaces a las plantillas, agregar una pequeña explicación de para que sirve cada una
- [x] Si es necesario/vale la pena, cambiar las plantillas para que reflejen un poco más la realidad de nuestros repositorios, importante mantener la sección de la licencia

**Comment by ManuelStardust** [comment]
Comando para generar la llave SSH:
ssh-keygen -t ed25519 -C "email@dominio.com"

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/.github/38?planning-poker) with Zenhub @hacheG
